import { test, expect } from '@playwright/test';

test('style shortcut settings apply tags/classes, persist, clear, and isolate projects', async ({ page }) => {
  test.setTimeout(180000);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/htzojicodwueivybovhy.supabase.co/**', route => route.fulfill({status:503, body:'offline test'}));
  await page.goto('/', {waitUntil:'domcontentloaded'});
  await page.locator('.new-book').click();
  await page.locator('#title').fill('스타일 단축키');
  await page.locator('#add').click();
  await page.waitForFunction(() => window.epubMonacoEditor && document.querySelector('.ProseMirror'));
  await page.locator('[data-mode-toggle]').click();
  await page.evaluate(() => window.epubMonacoEditor.setValue('<p id="target" class="keep">Alpha Beta Gamma</p>'));
  await page.locator('[data-mode-toggle]').click();
  const source = () => page.evaluate(() => window.epubMonacoEditor.getValue());
  const initial = await source();
  const css = await page.locator('#css').inputValue();
  const dialog = page.getByRole('dialog', {name:'텍스트 스타일 설정'});
  const openStyle = async id => {
    await page.locator('[data-heading]').selectOption('add-style');
    await dialog.locator('[name=style]').selectOption(id);
  };
  const record = async keys => {
    await dialog.locator('[name=shortcut]').focus();
    await page.keyboard.press(keys);
  };
  const save = () => dialog.getByRole('button', {name:'저장', exact:true}).click();
  await openStyle('h1');
  await record('Control+Alt+7');
  await expect(dialog.locator('[name=shortcut]')).toHaveValue('Ctrl/Cmd + ALT + 7');
  await save();
  await openStyle('p');
  await record('Control+Alt+7');
  await expect(dialog.locator('[role=alert]')).toContainText('이미');
  await record('Control+s');
  await expect(dialog.locator('[role=alert]')).toContainText('사용할 수 없는');
  await record('Control+Alt+8');
  await save();
  expect(await source()).toBe(initial);
  expect(await page.locator('#css').inputValue()).toBe(css);

  await openStyle('new');
  await dialog.locator('[name=label]').fill('강조문');
  await dialog.locator('[name=target]').fill('highlight-text');
  await record('Control+Alt+9');
  await save();
  const customCss = await page.locator('#css').inputValue();
  const target = page.locator('.ProseMirror #target');
  await target.click();
  await page.keyboard.press('Control+Alt+7');
  await expect(page.locator('.ProseMirror h1#target')).toHaveClass('keep');
  await expect.poll(source).toContain('<h1');
  await page.keyboard.press('Control+Alt+8');
  await expect(page.locator('.ProseMirror p#target')).toHaveClass('keep');
  await page.keyboard.press('Control+Alt+9');
  await page.keyboard.press('Control+Alt+9');
  await expect(target).toHaveClass('keep highlight-text');
  await expect(page.locator('#preview p.highlight-text')).toHaveText('Alpha Beta Gamma');
  await page.evaluate(() => {
    const text = document.querySelector('.ProseMirror #target').firstChild;
    const range = document.createRange(); range.setStart(text,6); range.setEnd(text,10);
    const selection = getSelection(); selection.removeAllRanges(); selection.addRange(range);
    document.querySelector('.ProseMirror').dispatchEvent(new MouseEvent('mouseup', {bubbles:true}));
  });
  await page.keyboard.press('Control+Alt+9');
  await expect(target.locator('span.highlight-text')).toHaveText('Beta');
  expect(await page.locator('#css').inputValue()).toBe(customCss);
  // Outside general-edit focus, the binding must not apply to the chapter.
  const applied = await source();
  await page.locator('#ctitle').focus();
  await page.keyboard.press('Control+Alt+7');
  expect(await source()).toBe(applied);
  await page.locator('[data-mode-toggle]').click();
  await page.evaluate(() => window.epubMonacoEditor.focus());
  await page.keyboard.press('Control+Alt+7');
  expect(await source()).toBe(applied);
  await page.keyboard.press('Control+s');
  await expect(page.locator('#status')).toContainText('저장');
  await page.reload({waitUntil:'domcontentloaded'});
  await page.waitForFunction(() => window.epubMonacoEditor && document.querySelector('.ProseMirror'));
  await expect(page.locator('#title')).toHaveValue('스타일 단축키');
  await openStyle('h1');
  await expect(dialog.locator('[name=shortcut]')).toHaveValue('Ctrl/Cmd + ALT + 7');
  await dialog.getByRole('button', {name:'닫기', exact:true}).click();
  await target.click();
  await page.keyboard.press('Control+Alt+7');
  await expect(page.locator('.ProseMirror h1#target')).toBeVisible();
  await openStyle('h1');
  await record('Control+Alt+Shift+7');
  await save();
  await target.click();
  await page.keyboard.press('Control+Alt+8');
  await page.keyboard.press('Control+Alt+7');
  await expect(page.locator('.ProseMirror p#target')).toBeVisible();
  await page.keyboard.press('Control+Alt+Shift+7');
  await expect(page.locator('.ProseMirror h1#target')).toBeVisible();
  await openStyle('h1');
  await dialog.getByRole('button', {name:'단축키 해제'}).click();
  await save();
  await target.click();
  await page.keyboard.press('Control+Alt+8');
  await page.keyboard.press('Control+Alt+Shift+7');
  await expect(page.locator('.ProseMirror p#target')).toBeVisible();
  await page.locator('.new-book').click();
  await page.locator('#add').click();
  await openStyle('p');
  await expect(dialog.locator('[name=shortcut]')).toHaveValue('');
  await dialog.locator('[name=style]').selectOption('h1');
  await expect(dialog.locator('[name=shortcut]')).toHaveValue('');
  await dialog.getByRole('button', {name:'닫기',exact:true}).click();
  await page.locator('.ProseMirror').click();
  const fresh = await source();
  await page.keyboard.press('Control+Alt+9');
  expect(await source()).toBe(fresh);
  expect(errors).toEqual([]);
});
