import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import JSZip from 'jszip';
import { mockApprovedSession, openSavedServerProject } from './approved-session.js';

test('스타일 대상·라벨과 공통 CSS 분리, XHTML·저장·프로젝트 격리', async ({ page }) => {
  test.setTimeout(180000);
  await mockApprovedSession(page);
  await page.goto('/', { waitUntil:'domcontentloaded' });
  await page.locator('.new-book').click();
  await page.locator('#title').fill('스타일 회귀');
  await page.locator('#add').click();
  await page.waitForFunction(() => window.epubMonacoEditor && document.querySelector('.ProseMirror'));
  await page.locator('[data-mode-toggle]').click();
  await page.evaluate(() => window.epubMonacoEditor.setValue('<h1 id="chapter-title">Title</h1><p id="target" class="original">Alpha Beta Gamma <a href="#chapter-title">1</a></p>'));
  await page.locator('[data-mode-toggle]').click();
  const editor = page.locator('.ProseMirror');
  await expect(editor.locator('#target')).toContainText('Alpha Beta');
  await page.evaluate(() => { const css = document.querySelector('#css'); css.value = '/* USER CSS */\nh1 { font-size: 32px; }\n.highlight-text { color: #d97706; }\n.quote-box { line-height: 1.8; }\n.original { margin: 7px; }\n'; css.dispatchEvent(new Event('input', { bubbles:true })); });
  const cssBefore = await page.locator('#css').inputValue();
  const dialog = page.getByRole('dialog', { name:'텍스트 스타일 설정' });
  await page.locator('[data-heading]').selectOption('add-style');
  await dialog.locator('[name=style]').selectOption('h1');
  await dialog.locator('[name=label]').fill('대제목');
  await expect(dialog.locator('[name=target]')).toHaveValue('h1');
  await expect(dialog.locator('[name=target]')).toBeDisabled();
  await dialog.getByRole('button', { name:'저장', exact:true }).click();
  await expect(page.locator('[data-heading] option[value=h1]')).toHaveText('대제목');
  await expect(page.frameLocator('.preview-isolated-frame').locator('h1').first()).toHaveCSS('font-size', '32px');
  await expect(editor.locator('h1')).toHaveCSS('font-size', '32px');
  expect(await page.locator('#css').inputValue()).toBe(cssBefore);
  await page.evaluate(() => { const css = document.querySelector('#css'); css.value = css.value.replace('32px', '36px'); css.dispatchEvent(new Event('input', { bubbles:true })); });
  await expect(editor.locator('h1')).toHaveCSS('font-size', '36px');
  await expect(page.frameLocator('.preview-isolated-frame').locator('h1')).toHaveCSS('font-size', '36px');
  await page.evaluate(() => { const css = document.querySelector('#css'); css.value = css.value.replace('36px', '32px'); css.dispatchEvent(new Event('input', { bubbles:true })); });
  const source = () => page.evaluate(() => window.epubMonacoEditor.getValue());
  const original = await source();
  expect(original).toBe('<h1 id="chapter-title">Title</h1><p id="target" class="original">Alpha Beta Gamma <a href="#chapter-title">1</a></p>');
  async function addStyle(label, className) {
    await page.locator('[data-heading]').selectOption('add-style');
    await dialog.locator('[name=style]').selectOption('new');
    await dialog.locator('[name=label]').fill(label);
    await dialog.locator('[name=target]').fill(className);
    await dialog.getByRole('button', {name:'저장', exact:true}).click();
  }
  await addStyle('강조문', 'highlight-text');
  expect(await source()).toEqual(original);
  const selectionPoints = await page.evaluate(() => {
    const text = document.querySelector('.ProseMirror #target').firstChild;
    const point = offset => {
      const range = document.createRange(); range.setStart(text, offset); range.collapse(true);
      const rect = range.getBoundingClientRect(); return {x:rect.x,y:rect.y + rect.height / 2};
    };
    return [point(6),point(10)];
  });
  await page.mouse.move(selectionPoints[0].x,selectionPoints[0].y);
  await page.mouse.down();
  await page.mouse.move(selectionPoints[1].x,selectionPoints[1].y,{steps:4});
  await page.mouse.up();
  await expect.poll(() => page.evaluate(() => getSelection()?.toString())).toBe('Beta');
  await page.locator('[data-heading]').selectOption({label:'강조문'});
  await expect(editor.locator('span.highlight-text')).toHaveText('Beta');
  await expect(editor.locator('span.highlight-text')).toHaveCSS('color', 'rgb(217, 119, 6)');
  await expect.poll(source).toContain('class="highlight-text"');
  await addStyle('인용 박스', 'quote-box');
  await page.locator('[data-mode-toggle]').click();
  await page.locator('[data-mode-toggle]').click();
  await editor.locator('#target').click({position:{x:20,y:10}});
  await page.keyboard.press('ArrowRight');
  await expect.poll(() => page.evaluate(() => getSelection()?.toString())).toBe('');
  await page.locator('[data-heading]').selectOption({label:'인용 박스'});
  await expect(editor.locator('p#target')).toHaveClass('original quote-box');
  await expect(editor.locator('a')).toHaveAttribute('href', '#chapter-title');
  await page.locator('[data-heading]').selectOption('add-style');
  await dialog.locator('[name=style]').selectOption({label:'강조문'});
  await expect(dialog.locator('[name=target]')).toBeDisabled();
  await dialog.locator('[name=label]').fill('포인트문장');
  await dialog.getByRole('button', {name:'저장', exact:true}).click();
  const applied = await source();
  await page.locator('[data-heading]').selectOption('add-style');
  await dialog.locator('[name=style]').selectOption({label:'포인트문장'});
  page.once('dialog', dialog => dialog.accept());
  await dialog.locator('[data-style-delete]').click();
  expect(await source()).toEqual(applied);
  const css = await page.locator('#css').inputValue();
  expect(css).toBe(cssBefore);
  expect(css).not.toContain('JH-STUDIO');
  expect(css).toContain('.highlight-text {');
  expect(css).toContain('.quote-box {');
  await page.keyboard.press('ControlOrMeta+s');
  await expect(page.locator('#status')).toContainText('저장');
  await page.waitForTimeout(600);
  await page.reload({waitUntil:'domcontentloaded'});
  await page.waitForFunction(() => window.epubMonacoEditor && document.querySelector('.ProseMirror'));
  await openSavedServerProject(page,'스타일 회귀');
  await expect(page.locator('#title')).toHaveValue('스타일 회귀');
  await expect(page.locator('[data-heading] option[value=h1]')).toHaveText('대제목');
  expect(await page.locator('#css').inputValue()).toEqual(css);
  expect(await source()).toContain('highlight-text');
  const downloading = page.waitForEvent('download');
  await page.locator('#export').click();
  const download = await downloading;
  const zip = await JSZip.loadAsync(await readFile(await download.path()));
  expect(await zip.file('EPUB/styles/book.css').async('string')).toEqual(css);
  const xhtmlFiles = Object.keys(zip.files).filter(path => path.endsWith('.xhtml'));
  const xhtml = (await Promise.all(xhtmlFiles.map(path => zip.file(path).async('string')))).join('');
  expect(xhtml).toContain('highlight-text'); expect(xhtml).toContain('original quote-box');
  await page.locator('input[type=file][accept^=".epub"]').setInputFiles(await download.path());
  const leaveImport=page.getByRole('dialog',{name:'미저장 변경 이탈 확인'});
  await expect.poll(async () => await leaveImport.isVisible() || (await page.locator('#status').textContent())?.includes('불러왔')).toBe(true);
  if (await leaveImport.isVisible()) await leaveImport.getByRole('button',{name:'변경 버리고 이동'}).click();
  await expect(page.locator('#status')).toContainText('불러왔');
  await expect(page.locator('[data-heading] option[value=h1]')).toHaveText('제목 1');
  await expect(page.locator('[data-heading] optgroup')).toHaveCount(0);
  expect(await page.locator('#css').inputValue()).toEqual(css);
  await page.locator('.new-book').click();
  await page.getByRole('dialog',{name:'미저장 변경 이탈 확인'}).getByRole('button',{name:'변경 버리고 이동'}).click();
  await expect(page.locator('[data-heading] option[value=h1]')).toHaveText('제목 1');
  await expect(page.locator('[data-heading] optgroup')).toHaveCount(0);
  await expect(page.locator('#css')).toHaveValue('');
  await expect.poll(() => page.locator('style[data-editor-typography]').textContent()).toBe('');
  await page.locator('#title').fill('다른 스타일 프로젝트');
  await page.locator('.draft-save').click();
  await expect(page.locator('#status')).toContainText('서버 저장 완료');
  await openSavedServerProject(page,'스타일 회귀');
  await expect(page.locator('[data-heading] option[value=h1]')).toHaveText('대제목');
  expect(await page.locator('#css').inputValue()).toEqual(css);
  await expect.poll(() => page.locator('style[data-editor-typography]').textContent()).toContain('.highlight-text { color: #d97706; }');
  await openSavedServerProject(page,'다른 스타일 프로젝트');
  await expect(page.locator('[data-heading] option[value=h1]')).toHaveText('제목 1');
  await expect(page.locator('[data-heading] optgroup')).toHaveCount(0);
  await expect.poll(() => page.locator('style[data-editor-typography]').textContent()).toBe('');
});

test('새 태그 스타일은 현재 블록에 적용되고 XHTML과 공통 CSS를 보존한다', async ({ page }) => {
  await mockApprovedSession(page);
  await page.goto('/', {waitUntil:'domcontentloaded'});
  await page.locator('.new-book').click();
  await page.locator('#add').click();
  await page.waitForFunction(() => window.epubMonacoEditor && document.querySelector('.ProseMirror'));
  await page.locator('[data-mode-toggle]').click();
  await page.evaluate(() => window.epubMonacoEditor.setValue('<p id="target">Quote text</p>'));
  await page.locator('[data-mode-toggle]').click();
  await page.evaluate(() => { const css = document.querySelector('#css'); css.value = 'blockquote { color: #d97706; }'; css.dispatchEvent(new Event('input', { bubbles:true })); });
  await page.locator('[data-heading]').selectOption('add-style');
  const dialog = page.getByRole('dialog', {name:'텍스트 스타일 설정'});
  await dialog.locator('[name=label]').fill('인용문');
  await dialog.locator('[name=kind][value=tag]').check();
  await dialog.locator('[name=target]').fill('blockquote');
  await dialog.getByRole('button', {name:'저장',exact:true}).click();
  await page.locator('.ProseMirror #target').click();
  await page.locator('[data-heading]').selectOption({label:'인용문'});
  await expect(page.locator('.ProseMirror blockquote p#target')).toHaveText('Quote text');
  await expect(page.locator('.ProseMirror blockquote')).toHaveCSS('color', 'rgb(217, 119, 6)');
  await expect.poll(() => page.evaluate(() => window.epubMonacoEditor.getValue())).toContain('<blockquote>');
  await expect(page.locator('#css')).toHaveValue('blockquote { color: #d97706; }');
});

test('가져온 EPUB에서 스타일 설정만 바꾸면 XHTML·이미지·목차와 기존 CSS를 보존한다', async ({ page }) => {
  test.setTimeout(180000);
  await mockApprovedSession(page);
  await page.goto('/', {waitUntil:'domcontentloaded'});
  await page.waitForFunction(() => window.epubMonacoEditor && document.querySelector('.ProseMirror'));
  page.once('dialog', dialog => dialog.accept());
  await page.locator('input[type=file][accept^=".epub"]').setInputFiles('기도먼저.epub');
  await expect(page.locator('#status')).toContainText('불러왔');
  const originalCss = await page.locator('#css').inputValue();
  await page.locator('#list .chapter:not(.cover-chapter)').last().click({position:{x:55,y:15}});
  await page.locator('[data-mode-toggle]').click();
  await page.locator('[data-heading]').selectOption('add-style');
  const dialog = page.getByRole('dialog', {name:'텍스트 스타일 설정'});
  await dialog.locator('[name=style]').selectOption('h1');
  await dialog.locator('[name=label]').fill('대제목');
  await dialog.getByRole('button', {name:'저장',exact:true}).click();
  expect(await page.locator('#css').inputValue()).toBe(originalCss);
  const downloading = page.waitForEvent('download');
  await page.locator('#export').click();
  const exported = await JSZip.loadAsync(await readFile(await (await downloading).path()));
  const source = await JSZip.loadAsync(await readFile('기도먼저.epub'));
  for (const path of Object.keys(source.files).filter(path => path.endsWith('.xhtml') || /\.(png|jpg|jpeg|gif|svg)$/.test(path))) {
    expect(await exported.file(path).async('uint8array'), path).toEqual(await source.file(path).async('uint8array'));
  }
});
